export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"
export const DELETE_ITEM_TO_CART = "DELETE_ITEM_TO_CART"
export const UPDATE_ITEM_TO_CART = "UPDATE_ITEM_TO_CART"


export const RESET_CART = "RESET_CART"